<?php
error_reporting(E_ERROR | E_WARNING | E_PARSE);

global $form_id,$form_title,$form_desc,$form_comp,$form_loc,$form_url;
//============================================================================================

function cnw_add_jobs($j_title, $j_desc, $j_company, $j_loc, $j_url, $j_poster){
//add job listing to the joblisting table in the wordpress database if all fields have data

global $wpdb;

$rows_affected = 0;
$table_data = array();
$table_data["job_title"]=$j_title;
$table_data["job_desc"]=$j_desc;
$table_data["job_company"]=$j_company;
$table_data["job_loc"]=$j_loc;
$table_data["job_url"]=$j_url;
$table_data["job_poster"]=$j_poster;
$table_data["job_post_date"]=date("m/d/Y");

foreach( $table_data as $key => $value){
if (strlen($value)==0) break;
}

if ($value==date("m/d/Y"))
{
$rows_affected = $wpdb->insert("wp_cnw_joblist", $table_data);

}
return $rows_affected;
}

//============================================================================================
function cnw_edit_job($job_id)
{
//delete or edit a job listing already posted if the form is completely filled out.
global $wpdb,$form_id,$form_title,$form_desc,$form_comp,$form_loc,$form_url,$table_data;


if (isset($_POST["DeleteJob"]))
{
$cnw_job_sql="DELETE FROM wp_cnw_joblist WHERE job_id = '".$job_id."' ";
$cnw_job_results= $wpdb->get_results($cnw_job_sql);
}
else
{
$form_complete='Y';
$array_keys = array_keys($_POST);
for( $i=0;$i<count($array_keys);$i++ ) { 
  if( $_POST[$array_keys[$i]] == '' ) { 
     $form_complete='N';
  } 
}
if ($form_complete=='Y')
{
$table_data["job_title"]=$_POST["job_title"];
$table_data["job_desc"]=$_POST["job_desc"];
$table_data["job_company"]=$_POST["job_company"];
$table_data["job_loc"]=$_POST["job_loc"];
$table_data["job_url"]=$_POST["job_url"];
$table_data["job_poster"]=$_POST["job_poster"];
$table_data["job_post_date"]=date("m/d/Y");
$rows_affected = $wpdb->update("wp_cnw_joblist", $table_data,array( 'job_id' => $job_id ));

}
}
//update the form
$cnw_job_sql="SELECT * FROM wp_cnw_joblist WHERE job_id = '".$job_id."' ";
$cnw_job_results= $wpdb->get_results($cnw_job_sql);

$form_id=$cnw_job_results[0]->job_id;
$form_title=$cnw_job_results[0]->job_title;
$form_desc=$cnw_job_results[0]->job_desc;
$form_comp=$cnw_job_results[0]->job_company;
$form_loc=$cnw_job_results[0]->job_loc;
$form_url=$cnw_job_results[0]->job_url;

}
//============================================================================================
//determine what function to run based on if the form is complete or the delete box is checked
//TODO Make this function load only on activation.

$cnw_user=wp_get_current_user();
$cnw_user_email=$cnw_user->user_email;
$search_api_key = get_option('cnw_job_search_api_key');
$job_page_url = get_option('cnw_job_page_url');
$job_is_private=get_option('job_is_private', '');


if (isset($_POST["UpdateListing"])){
  if (isset($_POST['cnw_job_search_api_key'])){
$search_api_key = $_POST['cnw_job_search_api_key'];
update_option('cnw_job_search_api_key', $search_api_key);
  }

    if (isset($_POST['cnw_job_page_url'])){
$job_page_url = $_POST['cnw_job_page_url'];
update_option('cnw_job_page_url', $job_page_url);
    }


  if (isset($_POST['job_is_private'])){
    update_option('job_is_private', 'checked');
    }
    else{
    update_option('job_is_private', '');
  }
  if($_POST['job_id']>0){
    cnw_edit_job($_POST['job_id']);
    }
    else{
    $rcount=cnw_add_jobs($_POST['job_title'],$_POST['job_desc'],$_POST['job_company'],$_POST['job_loc'],$_POST['job_url'],$_POST['job_poster']);
  }
}
//display the job entry and update form
?>
<div class="wrap">
<br><b>My Job Application Options</b><?php echo $job_form[0]; ?><br>
Enter your Indeed.com API key in the field below. Create a page/post then type {my_job_application} in the content section where you want the job listings to appear.  Enter the url of the page/post you created in the field below.
<form name="cnw_job_search_form" method="post" action="<?php echo str_replace( '%7E', '~', $_SERVER['REQUEST_URI']); ?>">
<p>
<input type="hidden" name="show_cnw_jobs" value="Y">
<input type="hidden" name="cnw_job_search_hidden" value="Y">
API Key:<input type="text" name="cnw_job_search_api_key" value="<?php echo $search_api_key; ?>" size="20">
Job Page URL:<input type="text" name="cnw_job_page_url" value="<?php echo $job_page_url; ?>" size="40">
<input type="checkbox" name="job_is_private" value='1' <?php echo $job_is_private; ?>> Joblist is private
</p>
To add a job complete all fields below with  except the indentification number field on the first line.  Press the button at the bottom of the form to upload the job.  The indentification number number will be generated by the server.<br>
Job ID<br><input type="text" name="job_id" value="<?php echo $form_id; ?>" size="3"> <em>(Enter a job ID to edit or delete an existing job listing, otherwise leave blank.)</em>
<div>
    Job Title<br />
    <input type="text" name="job_title" value="<?php echo $form_title; ?>" size="45"><input type="checkbox" name="DeleteJob" value='0' /> Delete job<br />
    Job Description:<br /><textarea name="job_desc" cols="50" rows="3"><?php echo $form_desc; ?></textarea><br />
    Company Name:<br /><input type="text" name="job_company" value="<?php echo $form_comp; ?>" size="55"><br />
    Job Location:<br /><input type="text" name="job_loc" value="<?php echo $form_loc; ?>" size="55"><br />
    Job URL:<br /><input type="text" name="job_url" value="<?php echo $form_url; ?>" size="55"><br />
    Job Poster's Email:<br /><input type="text" name="job_poster" value="<?php echo $cnw_user_email; ?>" size="55">
  </div><br />
<span class="submit"><input type="submit" name="UpdateListing" value="Update/View job listing" /></span>
</form>
</div>